# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-27 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('reality_type', models.CharField(choices=[('MAGIC', 'MAGIC'), ('ROBOTICS', 'ROBOTICS'), ('GAMING', 'GAMING'), ('MYTHOLOGY', 'MYTHOLOGY')], max_length=450, null=True)),
                ('question', models.CharField(max_length=450, unique=True)),
                ('choice1', models.CharField(max_length=450, null=True)),
                ('choice2', models.CharField(max_length=450, null=True)),
                ('choice3', models.CharField(max_length=450, null=True)),
                ('choice4', models.CharField(max_length=450, null=True)),
                ('correct_choice', models.CharField(max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bits_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('magicmarks', models.IntegerField(default=0)),
                ('roboticsmarks', models.IntegerField(default=0)),
                ('mythologymarks', models.IntegerField(default=0)),
                ('ques_answered', models.CharField(blank=True, default='', max_length=450)),
                ('last_question', models.IntegerField(default=0)),
                ('current_reality', models.IntegerField(default=0)),
                ('reality_played', models.CharField(blank=True, default='', max_length=450)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
