# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-03 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
