# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-17 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190303_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ques_answered',
            field=models.CharField(blank=True, default='', max_length=450),
        ),
    ]
