# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190317_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reality_played',
            field=models.CharField(blank=True, default='', max_length=450),
        ),
    ]
